---
output:
  html_document
---

<br>


## 时间序列处理基础

- [R时间序列处理入门](R_time_series.html)

## 空间数据处理基础

### 空间数据规格

- 数据规格：shp, tab, WKB/WKT, GeoJSON/TopoJSON, PostGIS...
- 工具库：GDAL(C/C++), GeoTools(Java), pyshp(Python), rgdal(R), sf(R)

### 空间计算
- 工具库：GEOS(C/C++), JTS(Java), shapely(Python), rgeos(R) 


### 空间索引
简单总结空间索引技术，就是一句话：点数据用Geohash，线、面数据用R树。下面是zhanlijun（美团->阿里）的一系列经典博文：

- [Geohash算法原理](http://www.cnblogs.com/LBSer/p/3310455.html)
- [空间索引1](http://www.cnblogs.com/LBSer/p/3392491.html)
- [空间索引2](http://www.cnblogs.com/LBSer/p/3403933.html)
- [地理围栏技术：判断点是否落在某多边形围栏内部](http://www.cnblogs.com/LBSer/p/4471742.html)


### 空间可视化

- [瓦片地图原理](https://segmentfault.com/a/1190000011276788)
- [R空间可视化入门](spatial_analysis_R_vis.html)
- [R绘制Geohash块](geohash_R_vis.html)
- 工具库/软件：Mapnik(C++, Python), GeoServer(Java), Leaflet(Javascript), Leaflet for R(R), folium(Python)
- [GeoServer基本使用方法](geoserver.html)

### 轨迹挖掘
- GPS噪点过滤
    - Mean Filter或Median Filter：按照相邻观测位置进行噪点过滤
    - 卡尔曼滤波：按照观测位置概率与动力学推断概率的复合概率进行位置平滑。[卡尔曼滤波原理](http://www.bzarg.com/p/how-a-kalman-filter-works-in-pictures/)、[Kalman与GPS](https://stackoverflow.com/questions/1134579/smooth-gps-data)、[pykalman应用于GPS](https://stackoverflow.com/questions/43377626/how-to-use-kalman-filter-in-python-for-location-data)
    - 启发式噪点过滤：speed-based filter，density-based clustering
- 停留点检测
    - 启发式算法：[微软亚洲研究院郑宇](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/Mining20user20similarity20based20on20location20history.pdf)
- 轨迹分段
    - 按照时间分段：比如只考虑最近8分钟的轨迹点，常用于线上应用，经典例子是实时路况
    - 按照时空特点分段：比如相邻两点的时间间隔超过6分钟；相邻转向超过120度；使用Douglas-Peucker压缩获得形状关键点，按照关键点分割；按照停留点分割；按照速度跃变分段
    - 按照业务信息分段：根据起点和终点抽取轨迹；根据配送任务分段轨迹
- 轨迹生成路网：[微软亚洲研究院郑宇](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/maps-from-GPS.pdf)
- 地图分区
    - 矢量分区：基于矢量形状的计算获取地图分区，[Python shapely](map_segmentation.html)
    - 栅格分区：基于图片计算获取地图分区，[微软亚洲研究院郑宇](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/mapsegmentation.pdf)
- 地图匹配
    - Hidden Markov Model：ST-Matching算法，可以看做是HMM的变种，[微软亚洲研究院郑宇](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/Map-Matching20for20Low-Sampling-Rate20GPS20Trajectories-cameraReady.pdf)

### 经典论文
- 地图匹配：输入一串GPS点，返回一串Link
    - Hidden Markov Model：[Map-Matching for Low-Sampling-Rate GPS Trajectories](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/Map-Matching20for20Low-Sampling-Rate20GPS20Trajectories-cameraReady.pdf)
    - Global Matching: [On Map-Matching Vehicle Tracking Data](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.73.7466&rep=rep1&type=pdf)
- 轨迹距离：根据海量轨迹获得任意两点之间的通行距离或通行时间
    - 统计法：[A Simple Baseline for Travel Time Estimation using Large-Scale Trip Data](http://delivery.acm.org/10.1145/3000000/2996943/a61-hongjian.pdf?ip=103.37.140.17&id=2996943&acc=CHORUS&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E6D218144511F3437&__acm__=1519287457_adca89a3efdf68474813607afa36fd04)
    - 神经网络：[A Unified Neural Network Approach for Estimating Travel Time and Distance for a Taxi Trip](https://arxiv.org/pdf/1710.04350.pdf)
- [基于摩拜单车轨迹数据的自行车道规划](bike_lane.html)